apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mongo-application-secrets
  annotations:
    replicator.v1.mittwald.de/replication-allowed: "true"
    replicator.v1.mittwald.de/replication-allowed-namespaces: "*"
data:
  hostname: {{ printf "%q" "jenkins-x-mongodb.jx" | b64enc }}
  port: {{ printf "%q" "27017" | b64enc }}
  username: {{ printf "%q" "root" | b64enc  }}
  password: {{ .Values.mongo.rootPassword | b64enc }}