# Default values for nexus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: gcr.io/jenkinsxio/nexus
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: nexus
  type: ClusterIP
  externalPort: 80
  internalPort: 8081
resources:
  # limits:
    # cpu: 100m
    # memory: 4Gi
  # requests:
    # cpu: 100m
    # memory: 2Gi
env:
  ENABLE_ANONYMOUS_ACCESS: false
  NEXUS_SECURITY_RANDOMPASSWORD: false
readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 30
  failureThreshold: 6
livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 30
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 100Gi
securityContext:
  fsGroup: 2000

defaultAdminPassword: local:simonjamesrowe/adminUser:password

ingress:
  name: nexus
  host: nexus.{{ .Requirements.ingress.domain }}
  {{- if .Requirements.ingress.tls.production }}
  secretName: "tls-{{ .Requirements.ingress.domain | replace "." "-" }}-p"
  {{- else }}
  secretName: "tls-{{ .Requirements.ingress.domain | replace "." "-" }}-s"
  {{- end }}
