{{- if  or (eq .Requirements.repository "nexus") (eq .Requirements.repository "") }}
enabled: true
{{- else }}
enabled: false
{{- end }}


service:
  dockerPort: 5000

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 100Gi
