adminUser:
  password: local:simonjamesrowe/adminUser:password
  username: admin
aws:
  accessKeyId: local:simonjamesrowe/aws:accessKeyId
  accessSecret: local:simonjamesrowe/aws:accessSecret
  hostedZoneId: local:simonjamesrowe/aws:hostedZoneId
docker:
  email: simon@simonjamesrowe.com
  password: local:simonjamesrowe/docker:password
  url: https://nexus-jx.simonjamesrowe.com/repository/docker
  username: admin
enableDocker: true
pipelineUser:
  email: simon@simonjamesrowe.com
  token: local:simonjamesrowe/pipelineUser:token
  username: simonrowe-bot
prow:
  hmacToken: local:simonjamesrowe/prow:hmacToken
