{{- if .Values.certmanager.enabled }}
{{- if eq .Values.certmanager.production "false" }}
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: "{{ .Requirements.ingress.tls.email }}"
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - selector:
        dnsNames:
        - "*.{{ .Requirements.ingress.domain }}"
        - "{{ .Requirements.ingress.domain}}"
      # ACME DNS-01 provider configurations
      dns01:
        route53:
          region: us-east-1
          hostedZoneID: {{ .Parameters.aws.hostedZoneId}}
          accessKeyID: {{ .Parameters.aws.accessKeyId}}
          secretAccessKeySecretRef:
            name: cert-manager-aws-creds
            key: accessSecret
{{- end }}
{{- end }}
